### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by 8h2a** [schwerpunkt/VocTrainer#1]
UI/input-method issues:
- [ ] text field `#typespot1` on change/keydown/paste/input instead of onKeyPress
- [ ] text field should be selected by default
- [ ] currently onKeyPress prevents using any key combination with [Ctrl]
- [ ] User should be able to change to number of suggestions/choices + store in local storage
- [x] Textfield empty + Enter => Don't know => show correct solution
- [x] Rename "I know that" button to "Never ask again" + make it not green.
- [x] Column-names/Headings should be formatted differently

Storage/State:
- [ ] save trainer-state to local storage after every answer.
- [ ] "Ask any"/... selection should b stored when changed.

Misc:
- [x] "Trainers" shouldn't be defined in the index.html as html. They should be loaded from a json file.
moved to #5 
- [ ] Rules shouldn't be hardcoded in the trainer js file. They should be defined in a json file.

Code:
- [x] Consistent indentations
- [x] `this` / prototypes #7

**Comment by schwerpunkt** [comment]
Trainer definition is up for discussion in #5 .
